# Global config
AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
    - Gemfile.lock
    - config.ru
    - log/**/*
    - tmp/**/*
    - test/**/*
    - spec/**/*

# Checks the length of lines in the source code
Metrics/LineLength:
  Max: 150
  Exclude:
    - '**/spec/**/*'

# Checks if the length of a method exceeds some maximum value
Metrics/MethodLength:
  CountComments: false
  Max: 50

# Checks if the length of a block exceeds some maximum value
Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'

# Checks that the ABC size of methods is not higher than the configured maximum
Metrics/AbcSize:
  Max: 45

# Enforces LF unix EOL
Layout/EndOfLine:
  EnforcedStyle: lf
