version: '2'

services:
  demo-tape-app:
    image: demo-tape-app
    build:
      context: .
      dockerfile: Dockerfile-development
    command: docker/app-up
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    volumes_from:
      - 'demo-tape-cachebox'
    env_file:
      - '.env-development'
    # Byebug halt fix
    # @see https://gist.github.com/briankung/ebfb567d149209d2d308576a6a34e5d8
    stdin_open: true
    tty: true

  # Allows gem files caching
  # @see https://medium.com/magnetis-backstage/how-to-cache-bundle-install-with-docker-7bed453a5800
  demo-tape-cachebox:
    image: busybox
    volumes:
      - /cachebox
