# docker-compose file
#
# Must be compatible with Amazon ECS rules
#  @see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html
#
version: '2'

services:
  # demo-tape-postgres:
  #   image: 'postgres:10.3-alpine'
  #   volumes:
  #     - 'postgres:/var/lib/postgresql/data'
  #   env_file:
  #     - '.env-production'

  demo-tape-redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'demo-tape-redis:/data'
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-tape-redis
        awslogs-region: us-east-1
        awslogs-stream-prefix: redis

  demo-tape-website:
    image: 223263753891.dkr.ecr.us-east-1.amazonaws.com/demo-tape-app:latest
    depends_on:
      # - 'postgres'
      - 'demo-tape-redis'
    # build: .
    command: docker/website-up
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    volumes_from:
      - 'demo-tape-cachebox'
    env_file:
      - '.env-production'
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-tape-website
        awslogs-region: us-east-1
        awslogs-stream-prefix: website
    # Byebug halt fix
    # @see https://gist.github.com/briankung/ebfb567d149209d2d308576a6a34e5d8
    stdin_open: true
    tty: true

  demo-tape-sidekiq:
    image: 223263753891.dkr.ecr.us-east-1.amazonaws.com/demo-tape-app:latest
    depends_on:
      # - 'postgres'
      - 'demo-tape-redis'
    # build: .
    command: docker/sidekiq-up
    volumes:
      - '.:/app'
    volumes_from:
      - 'demo-tape-cachebox'
    env_file:
      - '.env-production'
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-tape-sidekiq
        awslogs-region: us-east-1
        awslogs-stream-prefix: sidekiq

  demo-tape-cable:
    image: 223263753891.dkr.ecr.us-east-1.amazonaws.com/demo-tape-app:latest
    depends_on:
      - 'demo-tape-redis'
    # build: .
    command: docker/cable-up
    environment:
      - PORT=28080
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    volumes_from:
      - 'demo-tape-cachebox'
    env_file:
      - '.env-production'
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-tape-cable
        awslogs-region: us-east-1
        awslogs-stream-prefix: cable

  # Allows gem files caching
  # @see https://medium.com/magnetis-backstage/how-to-cache-bundle-install-with-docker-7bed453a5800
  demo-tape-cachebox:
    image: busybox
    volumes:
      - /cachebox

volumes:
  demo-tape-redis:
