# docker-compose file
#
# Must be compatible with Amazon ECS rules
#  @see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html
#
version: '2'

services:
  demo-tape-app:
    image: 223263753891.dkr.ecr.us-east-1.amazonaws.com/demo-tape-app:latest
    # build: .
    command: /app/docker/app-up
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    env_file:
      - '.env-production'
    logging:
      driver: awslogs
      options:
        awslogs-group: demo-tape-app
        awslogs-region: us-east-1
        awslogs-stream-prefix: app
