#! /bin/sh

# App startup

# Set bundle path to PATH to get bin files
export PATH="$PATH:$BUNDLE_PATH"

# # Install node modules
# yarn check || yarn install

# # Install gems if needed
# bin/bundle check || bin/bundle install

# Set current directory
cd /app


# Start processes
if [ $RAILS_ENV = 'production' ];then

  # Precompile assets
  bin/bundle exec rake assets:precompile --trace

  # Start foreman process manager
  foreman start -f Procfile

else

  # Start foreman process manager
  foreman start -f Procfile.dev
fi

