#! /bin/sh

# Website startup

# Set bundle path to PATH to get bin files
export PATH="$PATH:$BUNDLE_PATH"

# # Install node modules
# yarn check || yarn install

# # Install gems if needed
# bin/bundle check || bin/bundle install

# Set current directory
cd /app


# Start foreman process manager
if [ $RAILS_ENV = 'production' ];then
  foreman start -f Procfile
else
  foreman start -f Procfile.dev
fi

