# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= 'db/#{ENV['COMPOSE_PROJECT_NAME']}_development.sqlite3' %>

test:
  <<: *default
  url: <%= 'db/#{ENV['COMPOSE_PROJECT_NAME']}_test.sqlite3' %>

staging:
  <<: *default
  url: <%= 'db/#{ENV['COMPOSE_PROJECT_NAME']}_staging.sqlite3' %>

production:
  <<: *default
  url: <%= 'db/#{ENV['COMPOSE_PROJECT_NAME']}_production.sqlite3' %>
